### ISSUE TITLE
XBreader passing volume/chapter data url using 'series' configuration

### ISSUE THREAD

**Issue by yashas123** [chocolatkey/xbreader#14]
Please add the complete functionality for passing 'series' config. The url passed is simply taken and passed to Series.ts without fetching the data from url given in 'series' config.
I the series config like this : `series: "/api/chapters.json?comic=10&ordering=volume%2Cnum%2Csnum&n=1000"` and I get `Error 9500  this.volumes.forEach is not a function` and when I tried checking the value thats passed to forEach function by this.volumes (Using console.log(this.values)) it's simply a string url that I passed to 'series' config as it is.

**Comment by dasZGFz** [comment]
@yashas123 You have to make your own loader. A working implementation is on comicake: https://github.com/chocolatkey/comicake/blob/master/frontend/material/assets/js/controllers/reader_controller.js#L41

**Comment by yashas123** [comment]
@dasZGFz Ok I just used the loader from comicake, edited it as shown below:
```
window.onload = function(){

  if(window.xbreader && window.xbconfig){
    if(window.xbconfig.series){
      window.xbconfig.loader = (cid, wxs) => {
        return fetch("manifest.json").then(response => {
            if (!response.ok) {
                var error = new Error(response.statusText);
                error.message = response;
                throw error;
            }
            return response.json();
        }).then(webpub => {
            return fetch(window.xbconfig.series).then(response => {
                if (!response.ok) {
                    var error = new Error(response.statusText);
                    error.message = response;
                    throw error;
                }
                return response.json();
            }).then(data => {
                if(data.next)
                    console.warn("Too many chapters to list!");

                const chapters = data.results;
                let volumeData = [];
                let nVolume = 0;
                let currentVolume = {
                    no: false,
                    chapters: []
                };
                chapters.forEach(chapter => {
                    if(chapter.volume != nVolume) {
                        currentVolume.no = nVolume == 0 ? false : nVolume;
                        currentVolume.title = nVolume > 0 ? ("Volume " + nVolume) : null;
                        volumeData.push(currentVolume);
                        nVolume = chapter.volume;
                        currentVolume = {
                            "chapters": []
                        };
                    }
                    currentVolume["chapters"].push({
                        no: parseFloat(`${chapter.num}.${chapter.snum}`),
                        selected: chapter.slug == cid ? true : false,
                        title: chapter.title,
                        slug: chapter.slug
                    });
                });
                currentVolume["no"] = nVolume == 0 ? false : nVolume;
                currentVolume.title = nVolume > 0 ? ("Volume " + nVolume) : null;
                volumeData.push(currentVolume);
                webpub.metadata.xbr = {
                    volumes: volumeData
                };
                return Promise.resolve(webpub);
            });
        }).catch(error => {
            console.error(error);
            document.body.innerHTML = `<span class="br__notifier">Error: ${error.message}</span>`;
        });
      }
    }
    window.xbreader(window.xbconfig);
  }else{
    console.log("No config given");
  }
}
```
and now when I use this and try passing url to 'series' config, the function `this.publication.smartLoad` in Reader.ts runs like about 5700+ times until at the end it shows `Maximum call stack size exceeded`

The place this is especially occuring is due to this code that I have put in Publication.ts
```
get slug(): string{
      return this.slug;
    }
```

Of course I have replaced all uuid/uniqid with slug because I don't use UUID of django at all and only use slug. And then I find out that the values from data attributes on body tag of reader html file is being taken and stored to Publication pmetadata. Could you please explain how I could change from uuid to slug on this.

**Comment by dasZGFz** [comment]
@yashas123 I don’t have the time to go through your code. However, you should not be touching the typescript at all to initialize. You only need the end js and the end css.
