### ISSUE TITLE
A bug and some feature requests

### ISSUE THREAD

**Issue by yashas123** [chocolatkey/xbreader#19]
As for the bug:
The title tag value in head doesn't change when user navigates from one chapter to another. (Due to ajax links)
I think it's best to make the suffix of title tag to be passed through config. As I would want the title to be in this format "Chapter Title | Site Name", so maybe we pass `| <Site Name>` to config and it adds it to the title as it is given.

As for features:
1. Can you add something like a theme color changer or something like dark and light mode switcher.
2. Can you add support for comments, I would like to add disqus comments to the reader page.
3. Can you add support for ads, before the start and after the last pages.

Thank you.

**Comment by dasZGFz** [comment]
@yashas123 
For the feature requests: those are all things you can do yourself. There are hooks to do that embedded in the reader. https://github.com/chocolatkey/xbreader/blob/master/src/app/components/Reader.ts#L94

For the title bug: Please provide an implementation that reproduces this bug.

**Comment by yashas123** [comment]
@dasZGFz 
Hmm nothing I can say on when you ask for implementation.
When I go to a chapter from comic or homepage. Suppose there is link for Chapter and when I press it it goes to the reader.
See in image below it is now in chapter 33.3. Here the title is `Kenja no Mago Chapter 33.3 | Sitename`

![image](https://user-images.githubusercontent.com/25717245/55285853-48f76380-53b1-11e9-955c-bf5c938a6fbb.png)

And then I press on Next/Prev button or use the chapter selector from the top bar to navigate to another chapter

![image](https://user-images.githubusercontent.com/25717245/55285884-b7d4bc80-53b1-11e9-8b2b-902a4e20e358.png)

As you can now see from the top bar or even the url, chapter is 34.1 but the title remains the same `Kenja no Mago Chapter 33.3 | Sitename` (As shown in browser tab title on top in image)

**Comment by dasZGFz** [comment]
@yashas123 xbreader doesn't touch the title. It's up to the site to implement it.
