### ISSUE TITLE
How to make browser remember last used reading configuration by the user

### ISSUE THREAD

**Issue by yashas123** [chocolatkey/xbreader#22]
The reading configuration im talking about is the toggle reading direction and changing fit to height/width on reader.
Like for the sites https://whimsubs.xyz/ and http://reader.championscans.com, it remembers my last toggle or fit image settings. I know cookies/local storage can be used but just asking how to do it with this reader.

**Comment by dasZGFz** [comment]
@yashas123 Both those sites use xbreader and, more specifically, comicake. You can find the source code here to see how it saves settings: https://github.com/chocolatkey/comicake
