### ISSUE TITLE
Please Add Comments and Ads

### ISSUE THREAD

**Issue by yashas123** [chocolatkey/xbreader#35]
Can ads and comments be added to the reader please? This is a feature very much needed.
How I think the idea way would be is:
Supposedly I use disqus comments, I pass the code of the disqus to xbreader.config and then the reader adds an extra page at the end which has the comments code I have passed to it's config.
And same for ads. Since in horizontal reading mode the 1st page at right is empty, it can be used for inserting ads and also 1 ad at the last page before comments.
And make the comment page and ad page width and height 100% when in horizontal reading and make the height auto when in vertical reading.
I tried modifying the codes to do something similar as above but it didn't work out.

**Comment by dasZGFz** [comment]
@yashas123 Ads and comments will not be added to xbreader as it is outside the scope of the project. We offer enough customization that you can add it yourself at the end of the reader through the webpub.

**Comment by yashas123** [comment]
@dasZGFz Could you please give an example code where I could pass it from? is it from the webpub of the loader?
