### ISSUE TITLE
Mithrilify slider component

### ISSUE THREAD

**Issue by chocolatkey** [chocolatkey/xbreader#8]

**Comment by yashas123** [comment]
Can you please add next and previous chapter code. Even if I give the link in config as 'series':'/api/chapters.json?comic=10&ordering=volume%2Cnum%2Csnum&n=1000' it doesn't actually get the data from the link (I checked the code and there is no fetch done on the link, it's simply being passed to Series.ts) and also getting error like `this.volumes.forEach is not a function` when series link is passed. I logged the value of this.volumes to find it is the string url that I passed in config as it is.

**Comment by dasZGFz** [comment]
https://github.com/spacejack/mithril-range
https://bundlephobia.com/result?p=mithril-range@0.4.0
